import type { Metadata } from "next";
import { Archivo_Narrow, Hanken_Grotesk } from "next/font/google";
import "./globals.css";

import Nav from "@/components/nav";
import { ReactLenis } from "lenis/react";

const hankenGrotesk = Hanken_Grotesk({
  variable: "--font-hanken-grotesk",
  subsets: ["latin"],
});

const archiveNarrow = Archivo_Narrow({
  variable: "--font-archivo-narrow",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trident CPB Marine | Underwater Solutions, Marine Diving Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root />
      <body
        className={`${hankenGrotesk.variable} ${archiveNarrow.variable} antialiased overflow-x-hidden`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
