import type { Metadata } from "next";
import { Hanken_Grotesk, Roboto_Condensed } from "next/font/google";
import "./globals.css";

import Nav from "@/components/nav";

const hankenGrotesk = Hanken_Grotesk({
  variable: "--font-hanken-grotesk",
  subsets: ["latin"],
});

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trident CPB Marine | Underwater Solutions, Marine Diving Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hankenGrotesk.variable} ${robotoCondensed.variable} antialiased`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
